apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wmnfpdxw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-wmnfpdxw:04ff47e56a088d7a1d9e7eec92525c8a7b48cdab@sha256:ac459bbd1bb6f167e0f01d1a7a1166433067b93d30cea9c6276f5f93a128d2b8
          name: container-image
